### ISSUE TITLE
Add library to CircuitPython Community Bundle

### ISSUE THREAD

**Issue by kattni** [WarriorOfWire/CircuitPython_async#10]
Hello! I wanted to request that you add this library to the [CircuitPython Community Bundle](https://github.com/adafruit/CircuitPython_Community_Bundle), if you are interested in doing so.

Please do not feel obligated, and feel free to close this regardless.

Thank you!

**Comment by kvc0** [comment]
This has been merged. Thanks for including CircuitPython_async in the bundle!
