### ISSUE TITLE
Change duration of scheduled event

### ISSUE THREAD

**Issue by slimhan** [WarriorOfWire/CircuitPython_async#14]
Hello, I'm trying to make a midi arpeggiator. I tried other methods but your library is really precise in terms of midi latency. Thanks for your efforts! Is there a way to change the duration after the run starts? I've added a screenshot; the bpm value will be changing here. I'm very new on GitHub so I'm not sure if this is the right place to ask this, but I couldn't find any other contact info.

```
def run():
    duR = (1000/PPQN_MAX)/(get_bpm()/60)          ## = 60000/(24*bpmM) = 2500/bpm
    asynccp.schedule(frequency=Duration.of_milliseconds(duR), coroutine_function=count_PPQN)
    asynccp.schedule(frequency=80, coroutine_function=updates_UE)
    # asynccp.add_task(main())
    asynccp.run()

if __name__ == '__main__':
    run()
```

![Screen Shot 2021-10-25 at 18 56 19](https://user-images.githubusercontent.com/92894755/138732073-a064c29e-9c93-45e0-883b-25f19a413ea1.png)

**Comment by kvc0** [comment]
Hi @slimhan! Glad to hear CircuitPython_async is working for you.

`asynccp.schedule` returns a `ScheduledTask`, which has.. well, here's the first few lines of it:
```
class ScheduledTask:
    def change_rate(self, frequency):
        """ Update the task rate to a new frequency. Float hz or asynccp.time.Duration interval """
```

Note that the update currently takes effect after the current task period. I.e., if you're currently running at 10hz then you want to update to 100hz you might wait nearly 100 milliseconds before the 10hz schedule takes effect. Reach out if it's a problem but so far nobody has mentioned struggling with that limitation.

I'm also in the CircuitPython Discord (if you post about your project maybe @ me so I can be excited with you!) but it's fine to open issues against the repo directly here too. Happy hacking!

**Comment by slimhan** [comment]
Thank you for your response! I am experimenting with change_rate. I have a few other questions, I'll ask them through Discord. However there's a latency issue bugging me, it could be helpful for others too. So let me put it here...

I have this simple example code below. I'm printing three values: Current Time in ms, Difference in ms, and Counter value. The idea is I'm adding a scheduled event that repeats itself x times in a second. And I have a counter which prints every x times(x is represented with the "`Division`" in the code...). Ideally, I should see around a 1000ms difference between every print, right? The weird thing is this is correct when the "`Division`" is set below 17. However if I set it to 17 or more, the difference in ms increases, I no longer get 1000ms. What could be the reason behind this? 

```
import time
import asynccp
import asynccp.time as timeAsync
Duration = timeAsync.Duration

Counter = 0
prevT = 0
Division = 16

async def count_function():   
    global Counter ; global prevT
    Counter += 1
    if Counter % Division == 0:
        curT=time.monotonic_ns()        
        print(int(curT/1000000),int((curT-prevT)/1000000), Counter)  # Current Time in ms, Difference in ms, Counter
        prevT = curT

runCounter = asynccp.schedule(frequency=Duration.of_milliseconds(1000/Division), coroutine_function=count_function)

def run():    
    asynccp.run()

if __name__ == '__main__':
    run()
```
Also, another question is the "difference in ms" gets less accurate when I use`frequency=Division` instead of  `frequency=Duration.of_milliseconds(1000/Division)`. Setting "`Division`" below 17 makes no difference. Am I doing something wrong here?

**Comment by kvc0** [comment]
Sounds like a floating point arithmetic thing. Idk which microcontroller you're using but might be you're just seeing bad results with divisions. If you do your division into microseconds, or just specify whole Duration.of_microseconds units you'll probably have a better experience because there are fewer conversions - but probably I should just make durations internally do integer math when integer units are provided.

**Comment by kvc0** [comment]
@slimhan try using Duration.of_nanoseconds() with the tip of main. I submitted this change which will let you specify exact nanosecond intervals you want without any unit conversions messing the timing up: https://github.com/WarriorOfWire/CircuitPython_async/pull/15 

Note that, as always, your timing is limited to whatever the precision of the microcontroller you're using is and further by whatever the resolution of the monotonic_ns() function is on your CircuitPython port. There's only so much I can do with this library - and I dug into changing monotonic_ns() but it's definitely a bear! Usually I use asynccp for UI interactivity and soft-scheduling periodic tasks that don't have extremely strict timing requirements. When I have real microsecond deadlines I go c++ ;-). Anyway, let me know how you get on with this latest change

**Comment by kvc0** [comment]
Closing stale issue; feel free to reach out if something is wrong!
