### ISSUE TITLE
testing tasko using time.monotonic() with Circuitpython on nRF

### ISSUE THREAD

**Issue by dh-metre** [WarriorOfWire/CircuitPython_async#2]
FYI, following up on the last issue i raised (since closed).  Apologies to not respond to your reply until now.

The following is a test of time.monotonic() vs time.montonic_ns() module on CP on nRF:

```
import time

def	sleep_ns(delta_ns):
	then = time.monotonic_ns()
	while  time.monotonic_ns() - then <= delta_ns:
		pass

def	sleep(delta_s):
	delta_ns = int(delta_s * 1.0e9)
	then = time.monotonic_ns()
	while  time.monotonic_ns() - then <= delta_ns:
		pass

then = time.monotonic()
then_ns = time.monotonic_ns()

for j in range(100):
	# val = j * 0.001
	# val = j * 100000
	val = j * 0.0001
	for i in range(3):
		now = time.monotonic()
		now_ns = time.monotonic_ns()
		print(f"j: {j}; n: {now:6.6f}; n_ns: {now_ns}; d: {now - then:.5f}; d_ns: {now_ns - then_ns}; d_s: {(now_ns - then_ns) * 1.0e-9:.10f}; d_st: {(now_ns - then_ns) * 1.0e-9:.4f}")
		then = time.monotonic()
		then_ns = time.monotonic_ns()
		# time.sleep(val)
		# sleep_ns(val)
		sleep(val)
```

Sample output:

```
j: 0; n: 164261.684418; n_ns: 164261680511486; d: 0.00000; d_ns: 213626; d_s: 0.0002136259; d_st: 0.0002
j: 0; n: 164261.684418; n_ns: 164261683654786; d: 0.00000; d_ns: 335685; d_s: 0.0003356849; d_st: 0.0003
j: 0; n: 164261.684418; n_ns: 164261686676027; d: 0.00000; d_ns: 305166; d_s: 0.0003051659; d_st: 0.0003
j: 1; n: 164261.684418; n_ns: 164261689788823; d: 0.00000; d_ns: 366203; d_s: 0.0003662028; d_st: 0.0004
j: 1; n: 164261.684418; n_ns: 164261692901618; d: 0.00000; d_ns: 396734; d_s: 0.0003967339; d_st: 0.0004
j: 1; n: 164261.684418; n_ns: 164261696014414; d: 0.00000; d_ns: 396734; d_s: 0.0003967339; d_st: 0.0004
j: 2; n: 164261.684418; n_ns: 164261699157727; d: 0.00000; d_ns: 396734; d_s: 0.0003967339; d_st: 0.0004
j: 2; n: 164261.684418; n_ns: 164261702331545; d: 0.00000; d_ns: 396720; d_s: 0.0003967198; d_st: 0.0004
j: 2; n: 164261.684418; n_ns: 164261705444341; d: 0.00000; d_ns: 396721; d_s: 0.0003967208; d_st: 0.0004
j: 3; n: 164261.684418; n_ns: 164261708587654; d: 0.00000; d_ns: 427252; d_s: 0.0004272518; d_st: 0.0004
j: 3; n: 164261.684418; n_ns: 164261711853040; d: 0.00000; d_ns: 549324; d_s: 0.0005493236; d_st: 0.0005
j: 3; n: 164261.684418; n_ns: 164261715087894; d: 0.00000; d_ns: 518793; d_s: 0.0005187928; d_st: 0.0005
j: 4; n: 164261.684418; n_ns: 164261718353279; d: 0.00000; d_ns: 549324; d_s: 0.0005493236; d_st: 0.0005
j: 4; n: 164261.684418; n_ns: 164261721740723; d: 0.00000; d_ns: 640864; d_s: 0.0006408638; d_st: 0.0006
j: 4; n: 164261.684418; n_ns: 164261725067145; d: 0.00000; d_ns: 610347; d_s: 0.0006103467; d_st: 0.0006
j: 5; n: 164261.684418; n_ns: 164261728424084; d: 0.00000; d_ns: 640878; d_s: 0.0006408778; d_st: 0.0006
j: 5; n: 164261.684418; n_ns: 164261731872564; d: 0.00000; d_ns: 701900; d_s: 0.0007018996; d_st: 0.0007
j: 5; n: 164261.684418; n_ns: 164261735290540; d: 0.00000; d_ns: 732432; d_s: 0.0007324317; d_st: 0.0007
j: 6; n: 164261.746407; n_ns: 164261738739020; d: 0.00000; d_ns: 732419; d_s: 0.0007324186; d_st: 0.0007
j: 6; n: 164261.746407; n_ns: 164261742340090; d: 0.00000; d_ns: 854491; d_s: 0.0008544905; d_st: 0.0009
j: 6; n: 164261.746407; n_ns: 164261745880137; d: 0.00000; d_ns: 823972; d_s: 0.0008239716; d_st: 0.0008
j: 7; n: 164261.746407; n_ns: 164261749511725; d: 0.00000; d_ns: 915526; d_s: 0.0009155255; d_st: 0.0009
j: 7; n: 164261.746407; n_ns: 164261753143313; d: 0.00000; d_ns: 915526; d_s: 0.0009155255; d_st: 0.0009
j: 7; n: 164261.746407; n_ns: 164261756774915; d: 0.00000; d_ns: 885022; d_s: 0.0008850216; d_st: 0.0009
j: 8; n: 164261.746407; n_ns: 164261760467539; d: 0.00000; d_ns: 946045; d_s: 0.0009460444; d_st: 0.0009
j: 8; n: 164261.746407; n_ns: 164261764251717; d: 0.00000; d_ns: 1037599; d_s: 0.0010375986; d_st: 0.0010
j: 8; n: 164261.746407; n_ns: 164261768035895; d: 0.00000; d_ns: 1037599; d_s: 0.0010375986; d_st: 0.0010
j: 9; n: 164261.746407; n_ns: 164261771911627; d: 0.00000; d_ns: 1129153; d_s: 0.0011291523; d_st: 0.0011
j: 9; n: 164261.746407; n_ns: 164261775787359; d: 0.00000; d_ns: 1159671; d_s: 0.0011596702; d_st: 0.0012
j: 9; n: 164261.746407; n_ns: 164261779663091; d: 0.00000; d_ns: 1159671; d_s: 0.0011596702; d_st: 0.0012
j: 10; n: 164261.746407; n_ns: 164261783569341; d: 0.00000; d_ns: 1159671; d_s: 0.0011596702; d_st: 0.0012
```
Floating point resolution seems to be the cause of the issue that I had before.  The time difference calculation using time.monotonic() produces zero unless delta time gets big enough.

I ended up replacing time in tasko with the following code (not at all optimized) and started to see what I expected.

```
import time

class Time_ns:
	def __init__(self):
		pass

	def monotonic_ns(self):
		return time.monotonic_ns()

	def monotonic(self):
		ns, lhs, rhs = self._monotonic_float()
		lhs = lhs - int(lhs * 1.0e-4) * 1.0e4
		return lhs + rhs

	def _monotonic_float(self):
		tm_ns = time.monotonic_ns()
		tm_lhs = int(tm_ns * 1.0e-9) * 1000000000
		tm_rhs = tm_ns - tm_lhs
		return tm_ns ,tm_lhs * 1.0e-9, (tm_rhs * 1.0e-4) * 0.00001

	def _monotonic_binary(self):
		# this is not accurate
		tm_ns = time.monotonic_ns()
		tm_lhs = (tm_ns >> 29) << 29
		tm_rhs = tm_ns - tm_lhs
		return tm_ns, tm_lhs * 1.0e-9, (tm_rhs * 1.0e-4) * 0.00001

	def sleep_ns(self, delta_t_ns):
		then = time.monotonic_ns()
		while  time.monotonic_ns() - then <= delta_ns:
			pass

	def sleep(self, delta_s):
		delta_ns = int(delta_s * 1.0e9)
		then = time.monotonic_ns()
		while  time.monotonic_ns() - then <= delta_ns:
			pass
```

In loop.py in tasko replaced time module as follows:
```
from Time_ns import Time_ns
time = Time_ns()
# import time
```

Results:
```
task1: 10Hz; index: 10; spot_per: 0.12500; avg_per 0.10012, avg_var: +0.024880
task2: 10Hz; index: 10; spot_per: 0.12500; avg_per 0.10012, avg_var: +0.024880
task3: 10Hz; index: 10; spot_per: 0.12500; avg_per 0.10012, avg_var: +0.024880
task4: 50Hz; index: 51; spot_per: 0.00000; avg_per 0.01987, avg_var: -0.019867


task1: 10Hz; index: 10; spot_per: 0.12500; avg_per 0.10012, avg_var: +0.024881
task2: 10Hz; index: 10; spot_per: 0.12500; avg_per 0.10012, avg_var: +0.024881
task3: 10Hz; index: 10; spot_per: 0.12500; avg_per 0.10012, avg_var: +0.024881
task4: 50Hz; index: 51; spot_per: 0.06250; avg_per 0.01987, avg_var: +0.042634


task1: 10Hz; index: 10; spot_per: 0.12500; avg_per 0.10015, avg_var: +0.024854
task2: 10Hz; index: 10; spot_per: 0.12500; avg_per 0.10015, avg_var: +0.024854
task3: 10Hz; index: 11; spot_per: 0.06250; avg_per 0.10013, avg_var: -0.037629
task4: 50Hz; index: 51; spot_per: 0.06250; avg_per 0.01987, avg_var: +0.042630


task1: 10Hz; index: 10; spot_per: 0.12500; avg_per 0.10012, avg_var: +0.024882
task2: 10Hz; index: 10; spot_per: 0.12500; avg_per 0.10012, avg_var: +0.024882
task3: 10Hz; index: 9; spot_per: 0.12500; avg_per 0.10012, avg_var: +0.024882
task4: 50Hz; index: 48; spot_per: 0.06250; avg_per 0.01987, avg_var: +0.042632


task1: 10Hz; index: 10; spot_per: 0.12500; avg_per 0.10012, avg_var: +0.024882
task2: 10Hz; index: 10; spot_per: 0.12500; avg_per 0.10012, avg_var: +0.024882
task3: 10Hz; index: 10; spot_per: 0.12500; avg_per 0.10012, avg_var: +0.024882
task4: 50Hz; index: 52; spot_per: 0.00000; avg_per 0.01987, avg_var: -0.019866


task1: 10Hz; index: 10; spot_per: 0.06250; avg_per 0.10009, avg_var: -0.037591
task2: 10Hz; index: 10; spot_per: 0.06250; avg_per 0.10009, avg_var: -0.037591
task3: 10Hz; index: 10; spot_per: 0.12500; avg_per 0.10012, avg_var: +0.024883
task4: 50Hz; index: 51; spot_per: 0.06250; avg_per 0.01986, avg_var: +0.042635
```
I am sure there are better ways to deal with this, but thought this might be of interest to anyone traveling through here.

**Comment by kvc0** [comment]
Are you reporting an issue with the head of branch `main`? Though time.sleep _should_ be able to accept a parameter with 0, there's no reason for tasko to sleep for 0 or negative time. Hence [the check for sleep_time > 0](https://github.com/WarriorOfWire/tasko/blob/2c482bf9a7317205bd193a7eafb7b67d151b05e1/tasko/loop.py#L184). If there is an issue can you please state it clearly so I can understand?

Also I suspect your monotonic() math is incorrect =)

**Comment by dh-metre** [comment]
The issue I believe have identified is that time.monotonic() on nRF Circuitpython seems to interfere with the function of tasko.  

It seems this is a result of the precision of floating point during the time difference calculation.  The consequence is that tasks do not schedule as expected in tasko on nRF.

I can imagine i have may have made errors in monotonic. My goal was to replace the time functions with alternatives that had better time resolution.  When I did that (despite any errors) tasko started to function as expected.

In the first sample output above you can see how at the step size used n (float) changes after many iterations. The following illustrates the floating point precision issue for differencing using time.monotonic.  

```
Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 6.0.1 on 2020-12-28; Adafruit ItsyBitsy nRF52840 Express with nRF52840
>>> 
>>> 164261.746407 - 164261.684418
0.0
>>> 0.746407 - 0.684418
0.0619888
>>> 
```
Using montonic_ns to calculate difference suggests it's possible to almost resolve 100us steps on nRF (see values for d_st in the output log above).

This is the same issue that I was referring to in the first I reported here.

I have not tested this on any other circuitpython ports but it seems that this floating point resolution issue could exist on other CP variants as it seems to be present in CP Issue/PR discussions.

**Comment by kvc0** [comment]
Okay, I think I understand you to mean that time.monotonic_ns is achieving better scheduling consistency than time.monotonic. Does that sound right?

I read through the implementation of time.monotonic and time.monotonic_ns the other evening and looks like _ns is a bit simpler on some (maybe all i dunno) ports. Probably an improvement to just use it as it's likely to be the finest-grained cross-board integral time type available.

**Comment by dh-metre** [comment]
Yes.  I believe the resolution of time.monotonic() when you take the float difference is about 1/16th of a second. So when you try to do something faster the behavior seems corrupted in time.

Changing to time.monotonic does seem to resolve the issue on nRF (it seems to improve resolution down to almost 100us).  Regarding most general solution,  I agree from what i have read, it should be more universal.

**Comment by Neradoc** [comment]
The issue is that Circuitpython floats are single precision, that means 5-6 significant digits:
```py
>>> 164261.746407
164262.0
```
As a result sleeping on the difference between high values of `monotonic` gets inaccurate the longer the board is running, and it ends up being unable to differentiate millisecond values. In tasko that means this `sleep_seconds` difference will always be 0 for high enough values of `time.monotonic()` (with a 10 or 100Hz repeating task for example).

https://github.com/WarriorOfWire/tasko/blob/2c482bf9a7317205bd193a7eafb7b67d151b05e1/tasko/loop.py#L183-L189

There is a discussion on the loss of precision of `time.monotonic()`here:
https://github.com/adafruit/circuitpython/issues/3410

So durations should ideally be computed in ints with `monotonic_ns`, and then converted in seconds for passing to `time.sleep()`.

But `monotonic_ns` requires long ints and is not available on some M0 boards due to size restrictions, so the LED animation library handles it like that for example (making the animations lag after a while on small boards I believe).
https://github.com/adafruit/Adafruit_CircuitPython_LED_Animation/blob/312c0428e0697a997f7671a7c69bf3d5879a05f5/adafruit_led_animation/__init__.py#L19-L38

**Comment by kvc0** [comment]
I've submitted a change that passes tests and rebases time computation on monotonic_ns(). Thanks for reporting the issue - please let me know if it addresses your issue (or makes it worse :-) )

**Comment by kvc0** [comment]
Most m0 boards don't even have async/await enabled because there are a couple new error strings and whatnot that cause the builds to exceed allowed space. While tasko on m0 seems really nice, it's not a p0 concern until async/await was universal across them (like it is on m4's and other less-limited boards).

Closing this for now as it's pretty stale & main has moved on.
