### ISSUE TITLE
Removing/stopping a scheduled task

### ISSUE THREAD

**Issue by maholli** [WarriorOfWire/CircuitPython_async#7]
I keep finding myself in situations where I want to stop/remove a scheduled task, but it's quite tedious to remove a task from tasko at the moment. Maybe you can set me straight? 

For lack of a better example...
```python
class Widget:
    lowbatt=False

    async def power_hungry(self):
        # something that takes a lot of power
        pass

    async def check_battery(self):
        if battery_percent() < 10 
            if not self.lowbatt:
                self.lowbatt=True
                # remove battery-intensive tasks from scheduler
                # tasko.remove(coroutine_function)
        elif self.lowbatt:
            self.lowbatt=False
            # add the battery-intensive task back
            tasko.schedule(hz=1,coroutine_function=self.power_hungry)

widget=Widget()

tasko.schedule(hz=1,coroutine_function=widget.power_hungry)
tasko.schedule(hz=0.03,coroutine_function=widget.check_battery)

tasko.run()
```

The intent here is that our widget will stop doing its `power_hungry` task every second if the periodic `check_battery` task determines the widget has a low battery voltage. 

- I'd think removing the task is preferred over suspending to avoid a bunch of old tasks from hanging around. But then I suppose there's the concern of dynamic allocations when potentially adding tasks back.

**Comment by kvc0** [comment]
When we chatted before I understood you to mean something very different 😄 

This is a good feature, will add.

**Comment by kvc0** [comment]
Ahh, meant to "resolve with comment:"

https://github.com/WarriorOfWire/tasko/commit/1d499ad6fd1676e4f4d7615005b0d42591af7b9d
