### ISSUE TITLE
means to schedule function that runs every x seconds

### ISSUE THREAD

**Issue by Swieter** [WarriorOfWire/CircuitPython_async#9]
I've just started using Tasko.  Looks pretty cool and looking forward to trying it out.

I have a situation where I want something to run every 60 seconds.
Or maybe every five minutes.

It would be nice to be able to schedule these functions in some manner like "min" or "sec" instead of "hz".

**Comment by kvc0** [comment]
Yeah this seems like a pretty reasonable ask. I’ll add it when I find a few minutes at a computer

**Comment by kvc0** [comment]
Here ya go, hope you find it useful! https://github.com/WarriorOfWire/tasko/commit/e55adce167aa9f860f0d9c01232516523b27721f

**Comment by Swieter** [comment]
Cool!  I'll give it a try today in the system I'm working on.  I wonder if instead of 'duration' it should be 'interval'.  I'll see how it fits and works.

**Comment by Swieter** [comment]
It looks like you removed HZ capability.  Can the specifying in Seconds or in HZ coexist?

**Comment by Swieter** [comment]
Ohhh... I see "as frequency" now.

**Comment by Swieter** [comment]
OK - last post for a bit and I'll leave you alone.  

tasko.schedule(10, coroutine_function=liquid_level_update)
tasko.schedule(tasko.tasko_time.Duration.of_seconds(1), coroutine_function=sampling)

The above is example from my code.  Two things.  I think it would be more clear if we could still do HZ=10 or of_frequency(10), just to make the number more clear.

And I couldn't do "Duration.of_seconds(1)", I had to the full thing shown above.  
At the top of my program I only have "import tasko", like your example.  Something doesn't seem to be right.

**Comment by kvc0** [comment]
well you'll want to also `import asynccp.time.Duration as Duration` or something to just `Duration.of_seconds()`.
You can `frequency=10` or `frequency=Duration.of_seconds(1)` if you want. It's just a "frequency-like" constraint where a number is frequency-like and an asynccp.time.Duration is frequency-like as it has an as_frequency(). It doesn't use as_frequency internally though 😆
